version: '3.8'

services:
  # api:
  #   container_name: relay_api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - relay_network

  relay_postgres:
    container_name: relay_postgres
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - relay_network

networks:
  relay_network:
    driver: bridge

volumes:
  postgres_data: