export const tagTypes = [
    'Auth',
    'Clients',
    'User',
    'Users',
    'Cities',
    'Locations',
    'Containers',
    'Sizes',
    'Payments',
    'Cells',
    'CellStatuses',
    'CellRentals',
    'Panels',
    'Relays',
    'RelayAccess',
    'Statistics',
    'List',
    'Requests',
    'Admin',
    'Roles',
    'Permissions',
    'CurrentUser',
    'AdminAudit',
    'EmailLogs'
] as const;