export const tagTypes = [
    'Auth',
    'Clients',
    'User',
    'Cities',
    'Locations',
    'Containers',
    'Sizes',
    'Payments',
    'Cells',
    'CellStatuses',
    'CellRentals',
    'Panels',
    'Relays',
    'RelayAccess',
    'Statistics',
    'List',
    'Requests',
    'Admin'
] as const;