name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/tochkasklada
            
            # Обновляем код
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            
            # Устанавливаем права на выполнение скриптов
            make fix-permissions
            
            # Перезапускаем приложение
            make rebuild
            
            # Ждем запуска и применяем миграции
            sleep 10
            make migrate 