name: Deploy to VPS

on:
  push:
    branches:
      - main

# Добавляем concurrency группу
concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/tochkasklada
            
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            
            make fix-permissions

            mkdir -p server/logs
            sudo chown -R 1000:1000 server/logs
            sudo chmod 777 server/logs
            
            make rebuild
            
            sleep 10
            make migrate 